---
# Site
baseurl: "http://change-me.com"
title: "Blaupause"
enableRobotsTXT: true
googleAnalytics: ""
# Content
languageCode: "en-us"
defaultContentLanguage: "en"
# Formats
metaDataFormat: "yaml"
# -----------------------------
# DO NOT CHANGE BELOW THIS LINE
# -----------------------------
disableLiveReload: true
watch: false
---
